### ISSUE TITLE
Erro no speech

### ISSUE THREAD

**Issue by jardeldyonisio** [butia-bots/butia_behavior#31]
Traceback (most recent call last):
  File "/home/jardeldyonisio/butia_ws/src/butia_speech/nodes/speech_synthesizer.py", line 7, in <module>
    from espnet2.bin.tts_inference import Text2Speech
  File "/home/jardeldyonisio/.local/lib/python3.8/site-packages/espnet2/bin/tts_inference.py", line 21, in <module>
    from espnet2.tasks.tts import TTSTask
  File "/home/jardeldyonisio/.local/lib/python3.8/site-packages/espnet2/tasks/tts.py", line 29, in <module>
    from espnet2.tts.feats_extract.dio import Dio
  File "/home/jardeldyonisio/.local/lib/python3.8/site-packages/espnet2/tts/feats_extract/dio.py", line 11, in <module>
    import pyworld
  File "/home/jardeldyonisio/.local/lib/python3.8/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by PedroCorcaque** [comment]
There were two problems: The first in speech_recognizer and the second in speech_synthesizer.

For the first, tensorflow was updated to version 2.8 and ffmpeg was installed (needed to play audio using audio_player). The tf version was specified in the requirements file, but ffmpeg must be installed via apt. 

For the second problem the solution was just to wait for the pre-trained model to be downloaded. 

Fixes have been uploaded to main.
